package com.example.ui

object Localization {
    private val translations = mapOf(
        PosLanguage.EN to mapOf(
            "CASH" to "CASH",
            "UPI" to "UPI",
            "COLLECT" to "COLLECT",
            "ADD_TO_BILL" to "ADD TO BILL",
            "TOTAL_BILL" to "TOTAL BILL",
            "ITEMS" to "ITEMS",
            "CLEAR" to "CLEAR",
            "OFFLINE" to "OFFLINE",
            "ONLINE" to "ONLINE",
            "RECENT_SALES" to "Recent Sales",
            "NO_SALES_TODAY" to "No Sales Today",
            "SYNC_SUCCESS" to "Synced successfully!",
            "SYNC_CLOUD" to "Syncing sales to cloud...",
            "CASH_SALES" to "Cash Sales: ₹",
            "UPI_SALES" to "UPI Sales: ₹",
            "CHIPS" to "Chips",
            "WATER" to "Bottle 1L ₹20",
            "LOOSE_WATER" to "Loose Water ₹3/5",
            "LOOSE_WATER_S" to "Loose Water",
            "DRY_FRUITS" to "Dry Fruits",
            "NAMKEEN" to "Namkeen",
            "MEETHA_PAN" to "Meetha Pan",
            "SADA_PAN" to "Sada Pan",
            "ZARDA_PAN" to "Zarda Pan",
            "SPL_PAN" to "Spl Pan",
            "GOLD_FLAKE" to "Gold Flake",
            "CLASSIC" to "Classic",
            "LOOSE" to "Loose",
            "PACK" to "Pack",
            "ALIGN_BARCODE" to "Align barcode inside green frame",
            "MOCK_SCAN" to "Simulate Barcode Scan",
            "TAP_SCAN_PRE" to "Tapped physically or virtual trigger:",
            "SUCCESS_COLLECT" to "Collected successfully!",
            "CART" to "Cart",
            "CLEAR_CART" to "Clear Cart",
            "EMPTY_CART" to "Cart is empty",
            "PAY_CASH" to "Pay Cash",
            "PAY_UPI" to "Pay UPI",
            "SUBTOTAL" to "Subtotal",
            "TOTAL" to "Total"
        ),
        PosLanguage.HI to mapOf(
            "CASH" to "नकद (CASH)",
            "UPI" to "यूपीआई (UPI)",
            "COLLECT" to "प्राप्त करें",
            "ADD_TO_BILL" to "बिल में जोड़ें",
            "TOTAL_BILL" to "कुल बिल",
            "ITEMS" to "आइटम",
            "CLEAR" to "साफ़ करें",
            "OFFLINE" to "ऑफलाइन",
            "ONLINE" to "ऑनलाइन",
            "RECENT_SALES" to "हालिया बिक्री",
            "NO_SALES_TODAY" to "आज कोई बिक्री नहीं",
            "SYNC_SUCCESS" to "सफलतापूर्वक सिंक किया गया!",
            "SYNC_CLOUD" to "क्लाउड पर सिंक हो रहा है...",
            "CASH_SALES" to "नकद बिक्री: ₹",
            "UPI_SALES" to "UPI बिक्री: ₹",
            "CHIPS" to "चिप्स",
            "WATER" to "बोतल 1L ₹20",
            "LOOSE_WATER" to "खुला पानी ₹3/5",
            "LOOSE_WATER_S" to "खुला पानी",
            "DRY_FRUITS" to "सूखे मेवे",
            "NAMKEEN" to "नमकीन",
            "MEETHA_PAN" to "मीठा पान",
            "SADA_PAN" to "सादा पान",
            "ZARDA_PAN" to "जर्दा पान",
            "SPL_PAN" to "स्पेशल पान",
            "GOLD_FLAKE" to "गोल्ड फ्लैक",
            "CLASSIC" to "क्लासिक",
            "LOOSE" to "खुला",
            "PACK" to "पैक",
            "ALIGN_BARCODE" to "बारकोड को हरे फ्रेम के अंदर रखें",
            "MOCK_SCAN" to "बारकोड स्कैन सिम्युलेट करें",
            "TAP_SCAN_PRE" to "भौतिक या वर्चुअल ट्रिगर दबाया गया:",
            "SUCCESS_COLLECT" to "सफलतापूर्वक प्राप्त हुआ!",
            "CART" to "कार्ट",
            "CLEAR_CART" to "कार्ट खाली करें",
            "EMPTY_CART" to "कार्ट खाली है",
            "PAY_CASH" to "नकद भुगतान करें",
            "PAY_UPI" to "UPI भुगतान करें",
            "SUBTOTAL" to "उप-योग",
            "TOTAL" to "कुल"
        ),
        PosLanguage.TA to mapOf(
            "CASH" to "பணம் (CASH)",
            "UPI" to "யூபிஐ (UPI)",
            "COLLECT" to "சேகரி",
            "ADD_TO_BILL" to "பில்லில் சேர்க்க",
            "TOTAL_BILL" to "மொத்த பில்",
            "ITEMS" to "பொருட்கள்",
            "CLEAR" to "அழி",
            "OFFLINE" to "ஆஃப்லைன்",
            "ONLINE" to "ஆன்லைன்",
            "RECENT_SALES" to "சமீபத்திய விற்பனை",
            "NO_SALES_TODAY" to "இன்று விற்பனை இல்லை",
            "SYNC_SUCCESS" to "வெற்றிகரமாக ஒத்திசைக்கப்பட்டது!",
            "SYNC_CLOUD" to "மேகக்கணியுடன் ஒத்திசைக்கிறது...",
            "CASH_SALES" to "பண விற்பனை: ₹",
            "UPI_SALES" to "UPI விற்பனை: ₹",
            "CHIPS" to "சிப்ஸ்",
            "WATER" to "தண்ணீர் பாட்டில் 1L ₹20",
            "LOOSE_WATER" to "தனி தண்ணீர் ₹3/5",
            "LOOSE_WATER_S" to "தனி தண்ணீர்",
            "DRY_FRUITS" to "உலர் பழங்கள்",
            "NAMKEEN" to "நம்கீன்",
            "MEETHA_PAN" to "இனிப்பு பாக்கு",
            "SADA_PAN" to "சாதா பாக்கு",
            "ZARDA_PAN" to "ஜர்தா பாக்கு",
            "SPL_PAN" to "சிறப்பு பாக்கு",
            "GOLD_FLAKE" to "கோல்ட் பிளேக்",
            "CLASSIC" to "கிளாசிக்",
            "LOOSE" to "தனி",
            "PACK" to "பேக்",
            "ALIGN_BARCODE" to "பார்கோடை பச்சை சட்டகத்திற்குள் சீரமைக்கவும்",
            "MOCK_SCAN" to "பார்கோடு ஸ்கேன் போலி செய்க",
            "TAP_SCAN_PRE" to "இயல்பு அல்லது மெய்நிகர் தூண்டல்:",
            "SUCCESS_COLLECT" to "வெற்றிகரமாக சேகரிக்கப்பட்டது!",
            "CART" to "கார்ட்",
            "CLEAR_CART" to "கார்ட்டை அழிக்கவும்",
            "EMPTY_CART" to "கார்ட் காலியாக உள்ளது",
            "PAY_CASH" to "பணம் செலுத்துங்கள்",
            "PAY_UPI" to "UPI செலுத்துங்கள்",
            "SUBTOTAL" to "கூட்டுத்தொகை",
            "TOTAL" to "மொத்தம்"
        ),
        PosLanguage.TE to mapOf(
            "CASH" to "నగదు (CASH)",
            "UPI" to "యూపీఐ (UPI)",
            "COLLECT" to "వసూలు చేయి",
            "ADD_TO_BILL" to "బిల్లుకు జోడించు",
            "TOTAL_BILL" to "మొత్తం బిల్లు",
            "ITEMS" to "ఐటెమ్‌లు",
            "CLEAR" to "క్లియర్",
            "OFFLINE" to "ఆఫ్‌లైన్",
            "ONLINE" to "ఆన్‌లైన్",
            "RECENT_SALES" to "ఇటీవలి అమ్మకాలు",
            "NO_SALES_TODAY" to "ఈరోజు విక్రయాలు లేవు",
            "SYNC_SUCCESS" to "సమకాలీకరించబడింది!",
            "SYNC_CLOUD" to "క్లౌడ్‌తో సమకాలీకరిస్తోంది...",
            "CASH_SALES" to "నగదు అమ్మకాలు: ₹",
            "UPI_SALES" to "యూపీఐ అమ్మకాలు: ₹",
            "CHIPS" to "చిప్స్",
            "WATER" to "నీళ్ల సీసా 1L ₹20",
            "LOOSE_WATER" to "విడి నీరు ₹3/5",
            "LOOSE_WATER_S" to "విడి నీరు",
            "DRY_FRUITS" to "డ్రై ఫ్రూట్స్",
            "NAMKEEN" to "నమ్‌కీన్",
            "MEETHA_PAN" to "మీఠా పాన్",
            "SADA_PAN" to "సాదా పాన్",
            "ZARDA_PAN" to "జర్దా పాన్",
            "SPL_PAN" to "స్పెషల్ పాన్",
            "GOLD_FLAKE" to "గోల్డ్ ఫ్లేక్",
            "CLASSIC" to "క్లాసిక్",
            "LOOSE" to "విడి",
            "PACK" to "ప్యాక్",
            "ALIGN_BARCODE" to "బార్‌కోడ్‌ను గ్రీన్ ఫ్రేమ్‌లో ఉంచండి",
            "MOCK_SCAN" to "బార్‌కోడ్ స్కాన్ సిమ్యులేట్ చేయి",
            "TAP_SCAN_PRE" to "భౌతిక లేదా వర్చువల్ ట్రిగ్గర్ ప్రెస్ చేయబడింది:",
            "SUCCESS_COLLECT" to "విజయవంతంగా వసూలు చేయబడింది!",
            "CART" to "కార్ట్",
            "CLEAR_CART" to "కార్ట్‌ను ఖాళీ చేయి",
            "EMPTY_CART" to "కార్ట్ ఖాళీగా ఉంది",
            "PAY_CASH" to "నగదు చెల్లించండి",
            "PAY_UPI" to "UPI చెల్లించండి",
            "SUBTOTAL" to "ఉపమొత్తం",
            "TOTAL" to "మొత్తం"
        )
    )

    fun get(key: String, lang: PosLanguage): String {
        return translations[lang]?.get(key) ?: key
    }
}
